[package]
name = "integratedeck"
version.workspace = true
edition.workspace = true

[lib]
name = "integratedeck_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
dirs = "6"

ideck-core = { workspace = true }
ideck-surface = { workspace = true }
ideck-sd-host = { workspace = true }
ideck-comp-host = { workspace = true }
ideck-bridge = { workspace = true }
